package com.example.demo.adapter;

import com.example.demo.dto.ProviderVerifyResult;

import java.util.Map;

public interface OtpProviderAdapter {

    /**
     * Verifies the OTP/Token received from a specific provider ( e.g. Firebase , Twilio )
     * There can be multiple implementations of the providers based on the requirements
     *
     * @param providerToken The OTP/token received from the frontend (generated by the external provider).
     * @param meta          Optional metadata passed along with the token (e.g., requestId, phoneNumber).
     * @return Standardized response containing verification status and user details.
     */
    ProviderVerifyResult verify(String providerToken, Map<String, Object> meta);

    /**
     * Returns a unique key/name for the provider implementation.
     * Used to dynamically select the correct OTP adapter at runtime.
     *
     * @return String  Unique provider key (e.g., "FIREBASE", "TWILIO", "AWSSNS")
     */
    String providerKey();
}
